#pragma once

#include <stdint.h>

#define CH32_BLACKBOX_MAGIC        0x43483332UL
#define CH32_BLACKBOX_VERSION      3U
#define CH32_BLACKBOX_CAPACITY     32U
#define CH32_BLACKBOX_KEY_SIZE     16U
#define CH32_BLACKBOX_KEY_MAX      CH32_BLACKBOX_KEY_SIZE

#define CH32_EVENT_TYPE_METRIC     1U
#define CH32_EVENT_TYPE_FLAG       2U
#define CH32_EVENT_TYPE_BOOT       3U
#define CH32_EVENT_TYPE_RESET      4U

#define CH32_ESPNOW_MAX_PEERS              8U
#define CH32_ESPNOW_PENDING_HEARTBEATS     8U
#define CH32_HEARTBEAT_DEFAULT_INTERVAL_MS 5000UL
#define CH32_HEARTBEAT_MIN_INTERVAL_MS     100UL

#define CH32_NEIGHBOR_MAX_ENTRIES          8U
#define CH32_NEIGHBOR_MIN_TIMEOUT_MS       1000UL

#define CH32_NEIGHBOR_UNKNOWN  0U
#define CH32_NEIGHBOR_ALIVE    1U
#define CH32_NEIGHBOR_SILENT   2U
#define CH32_NEIGHBOR_DEGRADED 3U

#define CH32_ADAPTIVE_REASON_NEIGHBOR_SILENT     1U
#define CH32_ADAPTIVE_REASON_NEIGHBOR_RECOVERED  2U
#define CH32_ADAPTIVE_REASON_NEIGHBOR_DEGRADED   3U
#define CH32_ADAPTIVE_REASON_NEIGHBOR_HEALTHY    4U

#ifndef CH32_LOG_INTERNAL_SUCCESS_EVENTS
#define CH32_LOG_INTERNAL_SUCCESS_EVENTS 0
#endif

#ifndef CH32_BOOT_STORM_THRESHOLD
#define CH32_BOOT_STORM_THRESHOLD 3U
#endif

#ifndef CH32_BOOT_STABLE_MS
#define CH32_BOOT_STABLE_MS 60000UL
#endif

#ifndef CH32_MAX_METRIC_ALERTS
#define CH32_MAX_METRIC_ALERTS 8U
#endif
